spring:
  application:
    name: user-service
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://tiger:tiger@172.17.0.1:8081/eureka
  instance:
    prefer-ip-address: true