server:
  port: 8000
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://tiger:tiger@registercenter:8081/eureka
zuul:
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
  routes:
    user-service:
      path: /user/**
      serviceId: USER-SERVICE
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
